"""empty message

Revision ID: 0dd6f1a0a442
Revises: 277b97cb3ba9
Create Date: 2022-08-20 23:07:19.982510

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0dd6f1a0a442'
down_revision = '277b97cb3ba9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'venue', 'areas', ['area_state'], ['state'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'venue', type_='foreignkey')
    # ### end Alembic commands ###
