"""empty message

Revision ID: 277b97cb3ba9
Revises: 4f367edb167a
Create Date: 2022-08-20 23:01:38.865340

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '277b97cb3ba9'
down_revision = '4f367edb167a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('area')
    op.drop_constraint('venue_area_state_fkey', 'venue', type_='foreignkey')
    op.create_foreign_key(None, 'venue', 'areas', ['area_state'], ['state'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'venue', type_='foreignkey')
    op.create_foreign_key('venue_area_state_fkey', 'venue', 'area', ['area_state'], ['state'])
    op.create_table('area',
    sa.Column('state', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('city', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('state', name='area_pkey')
    )
    # ### end Alembic commands ###
