"""empty message

Revision ID: 4f367edb167a
Revises: ba7c0e684782
Create Date: 2022-08-20 22:28:22.165836

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f367edb167a'
down_revision = 'ba7c0e684782'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shows', sa.Column('start_time', sa.String(length=120), nullable=True))
    op.add_column('venue', sa.Column('area_state', sa.String(length=20), nullable=False))
    op.create_foreign_key(None, 'venue', 'area', ['area_state'], ['state'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'venue', type_='foreignkey')
    op.drop_column('venue', 'area_state')
    op.drop_column('shows', 'start_time')
    # ### end Alembic commands ###
