"""empty message

Revision ID: 6d52a9ce950a
Revises: 0dd6f1a0a442
Create Date: 2022-08-21 08:46:14.716684

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d52a9ce950a'
down_revision = '0dd6f1a0a442'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('areas', sa.Column('id', sa.Integer(), nullable=False))
    op.alter_column('areas', 'state',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    op.add_column('venue', sa.Column('area_id', sa.Integer(), nullable=False))
    op.drop_constraint('venue_area_state_fkey', 'venue', type_='foreignkey')
    op.create_foreign_key(None, 'venue', 'areas', ['area_id'], ['id'])
    op.drop_column('venue', 'area_state')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venue', sa.Column('area_state', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'venue', type_='foreignkey')
    op.create_foreign_key('venue_area_state_fkey', 'venue', 'areas', ['area_state'], ['state'])
    op.drop_column('venue', 'area_id')
    op.alter_column('areas', 'state',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    op.drop_column('areas', 'id')
    # ### end Alembic commands ###
