"""empty message

Revision ID: 989889fdc80a
Revises: 54cd7e0ef12c
Create Date: 2022-08-22 09:30:18.912303

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '989889fdc80a'
down_revision = '54cd7e0ef12c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('show')
    op.add_column('shows', sa.Column('id', sa.Integer(), nullable=False))
    op.add_column('shows', sa.Column('artist_name', sa.String(length=50), nullable=True))
    op.add_column('shows', sa.Column('artist_image_link', sa.String(length=120), nullable=True))
    op.add_column('shows', sa.Column('venue_name', sa.String(length=50), nullable=True))
    op.add_column('shows', sa.Column('start_time', sa.String(length=50), nullable=True))
    op.drop_constraint('shows_venue_id_fkey', 'shows', type_='foreignkey')
    op.drop_constraint('shows_artist_id_fkey', 'shows', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('shows_artist_id_fkey', 'shows', 'artist', ['artist_id'], ['id'])
    op.create_foreign_key('shows_venue_id_fkey', 'shows', 'venues', ['venue_id'], ['id'])
    op.drop_column('shows', 'start_time')
    op.drop_column('shows', 'venue_name')
    op.drop_column('shows', 'artist_image_link')
    op.drop_column('shows', 'artist_name')
    op.drop_column('shows', 'id')
    op.create_table('show',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('artist', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('venue', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('start_time', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='show_pkey')
    )
    # ### end Alembic commands ###
