"""empty message

Revision ID: ba7c0e684782
Revises: d718f25c6297
Create Date: 2022-08-20 22:20:24.359328

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba7c0e684782'
down_revision = 'd718f25c6297'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('areas')
    op.add_column('shows', sa.Column('start_time', sa.String(length=120), nullable=True))
    op.add_column('venue', sa.Column('area', sa.String(length=20), nullable=False))
    op.create_foreign_key(None, 'venue', 'area', ['area'], ['state'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'venue', type_='foreignkey')
    op.drop_column('venue', 'area')
    op.drop_column('shows', 'start_time')
    op.create_table('areas',
    sa.Column('state', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('city', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('state', name='areas_pkey')
    )
    # ### end Alembic commands ###
