"""empty message

Revision ID: d718f25c6297
Revises: b36059335c38
Create Date: 2022-08-20 21:45:25.087837

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd718f25c6297'
down_revision = 'b36059335c38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('area')
    op.add_column('venue', sa.Column('area', sa.String(length=20), nullable=False))
    op.create_foreign_key(None, 'venue', 'areas', ['area'], ['state'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'venue', type_='foreignkey')
    op.drop_column('venue', 'area')
    op.create_table('area',
    sa.Column('state', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('city', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('state', name='area_pkey')
    )
    # ### end Alembic commands ###
